version: '3'

volumes:
  db_data:
  app_data:
    driver: local

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    image: shop_project
    ports:
      - "8000:8000"
    depends_on:
      - db