# Generated by Django 5.0.3 on 2024-04-14 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_alter_orderitem_quantity_alter_productinfo_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="confirmemailtoken",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата генерации токена"
            ),
        ),
        migrations.AlterField(
            model_name="confirmemailtoken",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="confirm_email_tokens",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец токена",
            ),
        ),
        migrations.AlterField(
            model_name="productinfo",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_infos",
                to="backend.product",
                verbose_name="Продукт",
            ),
        ),
        migrations.AlterField(
            model_name="productinfo",
            name="shop",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_infos",
                to="backend.shop",
                verbose_name="Магазин",
            ),
        ),
    ]
