# Generated by Django 5.0.3 on 2024-04-15 11:11

import backend.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0003_alter_confirmemailtoken_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.CharField(
                max_length=20,
                unique=True,
                validators=[backend.validators.PhoneNumberValidator()],
                verbose_name="Телефон",
            ),
        ),
    ]
